# Тема “Вычисления с помощью Numpy”

## Задание 1

In [1]:
import numpy as np

In [2]:
b = np.array ([[1, 2, 3, 3, 1],
               [ 6, 8, 11, 10, 7]])

In [3]:
a = b.transpose()

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a=a.mean(axis = 0)

In [6]:
mean_a

array([2. , 8.4])

## Задание 2

In [7]:
a_centered = np.subtract(a, mean_a)

In [8]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

In [9]:
x = (a_centered [:,0])

In [10]:
y = (a_centered [:,1])

In [11]:
a_centered_sp=np.dot (x,y)

In [12]:
a_centered_sp

8.0

In [13]:
N = a_centered.shape[0]

In [14]:
N

5

In [15]:
S = a_centered_sp / (N-1)

In [16]:
S

2.0

## Задание 4

In [17]:
m = np.cov (b)

In [23]:
m

array([[1. , 2. ],
       [2. , 4.3]])

In [24]:
b [0][1]

2

In [25]:
S==b[0][1]

True

# Тема “Работа с данными в Pandas”

## Задание 1

In [26]:
import pandas as pd

In [27]:
authors = pd.DataFrame ({'author_id' : [1, 2, 3], 'author_name' : ['Тургенев', 'Чехов', 'Островский']},
                       columns = ['author_id', 'author_name'])

In [28]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [29]:
books = pd.DataFrame ({'author_id': [1, 1, 1, 2, 2, 3, 3],
                       'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                       'price' : [450, 300, 350, 500, 450, 370, 290]})

In [30]:
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2

In [31]:
authors_price = pd.merge (authors, books, on = 'author_id', how = 'inner')

In [32]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

In [33]:
top5 = authors_price.nlargest (5, 'price')

In [34]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 4

In [35]:
price_max = authors_price.groupby('author_name').agg({'price': 'max'})
price_max = price_max.rename(columns = {'price':'max_price'})
price_max

max_price
author_name           
Островский         370
Тургенев           450
Чехов              500

In [36]:
price_min = authors_price.groupby('author_name').agg({'price': 'min'})
price_min = price_min.rename(columns = {'price':'min_price'})
price_min

min_price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [37]:
price_mean = authors_price.groupby('author_name').agg({'price': 'mean'})
price_mean = price_mean.rename(columns = {'price':'mean_price'})
price_mean

mean_price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [38]:
authors_stat = pd.concat([price_max, price_min, price_mean], axis = 1 )
authors_stat

max_price  min_price  mean_price
author_name                                  
Островский         370        290  330.000000
Тургенев           450        300  366.666667
Чехов              500        450  475.000000

## Задание 5

In [40]:
cover = pd.DataFrame ({'cover' : ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']},
                       columns = ['cover'])

In [41]:
cover

cover
0  твердая
1   мягкая
2   мягкая
3  твердая
4  твердая
5   мягкая
6   мягкая

In [42]:
authors_price = pd.concat([authors_price, cover], axis = 1)

In [43]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [44]:
?pd.pivot_table

In [45]:
import numpy as np

In [48]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], 
                           aggfunc=np.sum, fill_value=0)

In [49]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [50]:
book_info.to_pickle('book_info.pkl')

In [51]:
book_info2 = pd.read_pickle('book_info.pkl')

In [52]:
book_info==book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True